### ISSUE TITLE
Blurring background image is slow

### ISSUE THREAD

**Issue by chrislim** [ceaseless-prayer/CeaselessIOS#164]
![image](https://cloud.githubusercontent.com/assets/469630/7662174/53fe2746-fb0e-11e4-8eba-9807a8cde131.png)

We'd like the user load time to be <1 second. This was done on an iPad Air, but I got feedback on the slow load time from someone on an iPhone 6.

**Comment by LIL717** [comment]
I tried adding a visual effect blur in interface builder to the root view controller background image.  I think the reason we weren't doing it before was that it didn't cover the page view controller (dots) at the bottom of the page, so I just extended the view and it is working.  It is  blurred a little differently than it was before, but its loading much faster.  I'll push it up so you can look at it.  If we keep it, then we can delete UIImageEffects class because we wouldn't be using it.

**Comment by nylim11** [comment]
Do you remember if we ended up doing that?

**Comment by chrislim** [comment]
I think we've made this change.
