### ISSUE TITLE
Background image should be same in all views

### ISSUE THREAD

**Issue by LIL717** [ceaseless-prayer/CeaselessIOS#28]
Background image for the day should be set in user defaults and used as background for all views.  Uniform blurring and tinting should be applied.

**Comment by chrislim** [comment]
I have gone through and tried to update the background in all appropriate places: 052a816958fc7c0f4556ae27a0162ade6271ebea

Haven't looked into getting the blurring and tinting uniformity.

I did notice two bug-like things:
1. when entering the menu, the image appears in a rectangle and then resizes or something like that.
2. since the image is being dynamically fetched from a server, sometimes the one on the scripture card changes (the card reloads) but the backgrounds are still the old one.

**Comment by LIL717** [comment]
this is looking much better

**Comment by LIL717** [comment]
This all looks very uniform now
