### ISSUE TITLE
When the prayer journal is empty, we should show a popover box with an arrow pointing to the plus sign

### ISSUE THREAD

**Issue by chrislim** [ceaseless-prayer/CeaselessIOS#46]
This box could say "Tap here to create a note."

**Comment by chrislim** [comment]
857a2193b1fc1992a731a4e9d7ccee0d63b130de
resolved.

**Comment by LIL717** [comment]
When the first note is added, if nobody is tagged, the note belongs to Me, after adding the note, the popover box is blocking the tab button for Me notes.  the only way to see that note is to add another and tag somebody so that the popover goes away.  This may be resolved if we decide to show all notes together and tag "self" on untagged notes.

**Comment by chrislim** [comment]
Yea, I think showing all notes together is preferable.
