### ISSUE TITLE
Name disappears when note added during sync

### ISSUE THREAD

**Issue by LIL717** [ceaseless-prayer/CeaselessIOS#65]
When I add a note to a person while the address book is syncing, that person ends up with no name in the People table when the syncing process is done.  This causes the Person View to crash when the person is selected from the People table.
This also happens when the person is chosen in Settings while syncing.

**Comment by chrislim** [comment]
I think this is because PersonInfo gets re-created every time a sync happens (PersonIdentifier is more stable). The old one gets cleaned up and the new one takes its place.

**Comment by chrislim** [comment]
I noticed that updateCeaselessContactFromABRecord is being called in multiple places and this could be a concurrency issue. If we make the tagged person picker use ceaseless contacts, it could mitigate the problem because then updating the contacts should happen in one code path only.

At the same time, we probably still should use some synchronization tools on the personidentifier objects to keep these concurrency issues from happening.

**Comment by chrislim** [comment]
I think i found a different solution to the problem. THe cleanup of orphaned records was happening separately, by cleaning up as we go, this should not be an issue because the persistentstorecoordinator/managed object context should take care of it for us.

**Comment by chrislim** [comment]
I believe 20f49a96 solves this.
