### ISSUE TITLE
User confused about appending vs adding new note

### ISSUE THREAD

**Issue by chrislim** [ceaseless-prayer/CeaselessIOS#98]
When we have a blank card we have a shortcut to add a new note, but when a note is added, we just show the note. One user did not realize that adding a new note happened through the "more" menu, so instead they appended to their original note and felt like it was a poor experience. How can we create a better experience? Should we have an add note shortcut always visible in the personcard for example?

**Comment by LIL717** [comment]
The first row could always be Add new note.  Although on the phone that takes up a lot of real estate.  Only 2 notes are visible on the iPhone 6 on a Person card and only 1  1/2 are visible without scrolling on the iPhone 4S. Maybe that first row could be shorter since it would only need to show "Add new Note"  or a button above the notes rows with an add icon "+"

**Comment by chrislim** [comment]
Now that we have an add note icon always visible we can not worry about this case.
